import type { BlockTemplateGroup } from './types'

export const boxesTemplates: BlockTemplateGroup = {
    // ===== PREMIUM MINIMALIST =====
    'boxes-essential-minimal': {
        id: 'boxes-essential-minimal',
        name: 'Essential Minimalist',
        category: 'minimal',
        description: 'Design ultra-épuré, bordures fines et typographie soignée',
        preview: {
            bgType: 'light',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#1f2937',
        },
        styles: {
            section: 'py-16 md:py-24 px-6 bg-white',
            container: 'max-w-6xl mx-auto',
            title: 'text-3xl md:text-4xl font-semibold tracking-tight text-slate-900 text-center mb-6',
            subtitle: 'text-base text-slate-500 max-w-2xl mx-auto mb-16',
            grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8',
            card: 'group p-8 bg-white border border-slate-200 rounded-xl transition-all duration-300 hover:border-slate-300 hover:shadow-sm',
            badge: 'w-10 h-10 rounded-lg bg-slate-50 flex items-center justify-center mb-6 transition-colors group-hover:bg-slate-100',
            itemTitle: 'text-lg font-semibold text-slate-900 mb-3',
            itemText: 'text-sm text-slate-600 leading-relaxed',
            icon: 'w-5 h-5 text-slate-600',
        }
    },
    'boxes-bento-refined': {
        id: 'boxes-bento-refined',
        name: 'Refined Bento',
        category: 'modern',
        description: 'Style bento moderne avec coins très arrondis et fonds doux',
        preview: {
            bgType: 'light',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#10b981',
        },
        styles: {
            section: 'py-20 md:py-28 px-6 bg-slate-50/50',
            container: 'max-w-7xl mx-auto',
            title: 'text-4xl md:text-5xl font-bold tracking-tighter text-slate-900 text-center mb-6',
            subtitle: 'text-lg text-slate-500 max-w-2xl mx-auto mb-20',
            grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
            card: 'p-10 bg-white rounded-[2.5rem] shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)] border-0 transition-transform duration-500 hover:-translate-y-1',
            badge: 'w-14 h-14 rounded-2xl bg-emerald-50 flex items-center justify-center mb-8',
            itemTitle: 'text-xl font-bold text-slate-900 mb-4 tracking-tight',
            itemText: 'text-[15px] text-slate-500 leading-relaxed font-normal',
            icon: 'w-7 h-7 text-emerald-600',
        }
    },
    'boxes-sophisticated-dark': {
        id: 'boxes-sophisticated-dark',
        name: 'Sophisticated Dark',
        category: 'bold',
        description: 'Sombre et luxueux, contrastes subtils et accents élégants',
        preview: {
            bgType: 'dark',
            layoutType: 'grid',
            columns: 2,
            accentColor: '#ffffff',
        },
        styles: {
            section: 'py-20 md:py-32 px-6 bg-slate-950',
            container: 'max-w-5xl mx-auto',
            title: 'text-3xl md:text-4xl font-medium tracking-tight text-white text-center mb-6',
            subtitle: 'text-base text-slate-400 max-w-2xl mx-auto mb-24 font-light',
            grid: 'grid grid-cols-1 md:grid-cols-2 gap-12',
            card: 'relative p-12 bg-slate-900/50 border border-white/5 rounded-3xl backdrop-blur-sm transition-colors hover:bg-slate-900/80',
            badge: 'inline-flex items-center justify-center px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-bold uppercase tracking-widest text-white/50 mb-8',
            itemTitle: 'text-2xl font-semibold text-white mb-4 tracking-tight',
            itemText: 'text-base text-slate-400 leading-relaxed font-light',
            icon: 'w-6 h-6 text-white',
        }
    },
    'boxes-swiss-architect': {
        id: 'boxes-swiss-architect',
        name: 'Swiss Architectural',
        category: 'minimal',
        description: 'Design rigoureux, structure de grille apparente et typographie forte',
        preview: {
            bgType: 'light',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#000000',
        },
        styles: {
            section: 'py-20 md:py-32 px-6 bg-white',
            container: 'max-w-7xl mx-auto',
            title: 'text-4xl md:text-6xl font-black tracking-tighter text-black uppercase mb-8 text-left border-b-4 border-black pb-8',
            subtitle: 'text-xl font-bold text-black uppercase tracking-widest text-left mb-24',
            grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-0 border-t border-l border-black',
            card: 'p-10 border-r border-b border-black flex flex-col items-start gap-8 transition-colors hover:bg-black group',
            badge: 'text-[11px] font-bold uppercase tracking-[0.3em] text-black border border-black px-3 py-1 group-hover:text-white group-hover:border-white transition-colors',
            itemTitle: 'text-2xl font-bold text-black uppercase tracking-tight leading-none group-hover:text-white transition-colors',
            itemText: 'text-sm text-black/70 leading-relaxed font-medium group-hover:text-white/70 transition-colors',
            icon: 'w-8 h-8 text-black group-hover:text-white transition-colors',
        }
    },
    'boxes-editorial-ivory': {
        id: 'boxes-editorial-ivory',
        name: 'Ivory Editorial',
        category: 'modern',
        description: 'Style éditorial sophistiqué, tons ivoire et proportions élégantes',
        preview: {
            bgType: 'light',
            bgValue: '#FDFCF5',
            layoutType: 'grid',
            columns: 2,
            accentColor: '#4A4A4A',
        },
        styles: {
            section: 'py-24 md:py-36 px-6 bg-[#FDFCF5]',
            container: 'max-w-5xl mx-auto',
            title: 'text-3xl md:text-5xl font-light italic tracking-tight text-[#1A1A1A] text-center mb-6 font-serif',
            subtitle: 'text-lg font-serif italic text-black/40 text-center mb-24',
            grid: 'grid grid-cols-1 md:grid-cols-2 gap-x-16 gap-y-24',
            card: 'relative flex flex-col gap-6 items-center text-center pb-8 border-b border-black/5',
            badge: 'text-xs italic text-black/40 mb-2',
            itemTitle: 'text-3xl font-light text-[#1A1A1A] tracking-tighter font-serif',
            itemText: 'text-base text-[#4A4A4A] leading-relaxed font-serif max-w-sm',
            icon: 'w-12 h-12 text-[#1A1A1A] opacity-20 font-serif not-italic flex items-center justify-center text-4xl mb-4',
        }
    },
    'boxes-brutalist-refined': {
        id: 'boxes-brutalist-refined',
        name: 'Brutalist Refined',
        category: 'bold',
        description: 'Style brut et audacieux avec des ombres marquées et des contours forts',
        preview: {
            bgType: 'accent',
            bgValue: '#FFEB00',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#000000',
        },
        styles: {
            section: 'py-20 md:py-28 px-6 bg-[#FFEB00]',
            container: 'max-w-6xl mx-auto',
            title: 'text-4xl md:text-5xl font-black italic tracking-tighter text-black mb-6 drop-shadow-[4px_4px_0px_#fff]',
            subtitle: 'text-lg font-black uppercase text-black mb-20 bg-white inline-block px-4 py-1 self-center border-2 border-black',
            grid: 'grid grid-cols-1 md:grid-cols-3 gap-8',
            card: 'p-8 bg-white border-4 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] flex flex-col gap-4 items-start transition-all hover:translate-x-[4px] hover:translate-y-[4px] hover:shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]',
            badge: 'bg-black text-white px-2 py-1 text-[10px] font-black uppercase tracking-wider',
            itemTitle: 'text-2xl font-black text-black leading-none uppercase',
            itemText: 'text-sm text-black font-bold opacity-80 leading-snug',
            icon: 'w-10 h-10 text-black',
        }
    },
    'boxes-glass-luminous': {
        id: 'boxes-glass-luminous',
        name: 'Frosted Glass',
        category: 'modern',
        description: 'Effet verre dépoli ultra-moderne avec reflets lumineux',
        preview: {
            bgType: 'gradient',
            bgValue: 'linear-gradient(135deg, #6366f1 0%, #a855f7 100%)',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#ffffff',
        },
        styles: {
            section: 'py-24 md:py-32 px-6 bg-gradient-to-br from-indigo-600 via-purple-600 to-pink-500',
            container: 'max-w-7xl mx-auto',
            title: 'text-4xl md:text-5xl font-bold tracking-tight text-white text-center mb-6 drop-shadow-sm',
            subtitle: 'text-lg text-white/70 max-w-2xl mx-auto text-center mb-24 font-medium',
            grid: 'grid grid-cols-1 md:grid-cols-3 gap-6',
            card: 'p-8 bg-white/10 backdrop-blur-xl border border-white/20 rounded-[2rem] shadow-2xl flex flex-col gap-6 items-center text-center transition-all hover:bg-white/20 hover:-translate-y-2',
            badge: 'px-4 py-1 rounded-full bg-white/20 text-white text-[10px] font-bold uppercase tracking-widest',
            itemTitle: 'text-xl font-bold text-white',
            itemText: 'text-sm text-white/80 leading-relaxed font-medium',
            icon: 'w-8 h-8 text-white drop-shadow-[0_0_8px_rgba(255,255,255,0.5)]',
        }
    },
    'boxes-cyber-mono': {
        id: 'boxes-cyber-mono',
        name: 'Cyber Tech',
        category: 'bold',
        description: 'Design technique monospace, angles vifs et accents néon',
        preview: {
            bgType: 'dark',
            bgValue: '#050505',
            layoutType: 'grid',
            columns: 2,
            accentColor: '#22c55e',
        },
        styles: {
            section: 'py-20 md:py-32 px-6 bg-[#050505]',
            container: 'max-w-5xl mx-auto',
            title: 'text-3xl md:text-4xl font-mono text-green-500 mb-6 flex items-center gap-4 before:content-[\'>\'] before:animate-pulse',
            subtitle: 'text-sm font-mono text-green-500/50 mb-20 block before:content-[\'--\']',
            grid: 'grid grid-cols-1 md:grid-cols-2 gap-px bg-green-500/20 border border-green-500/20',
            card: 'p-10 bg-[#0a0a0a] flex flex-col gap-6 items-start relative group font-mono overflow-hidden',
            badge: 'text-[10px] text-green-500/50 border border-green-500/20 px-2 py-0.5 uppercase tracking-tighter',
            itemTitle: 'text-lg font-mono font-bold text-green-500 uppercase tracking-widest group-hover:drop-shadow-[0_0_8px_rgba(34,197,94,0.5)]',
            itemText: 'text-xs text-green-500/70 leading-relaxed font-mono',
            icon: 'w-6 h-6 text-green-500',
        }
    },
    'boxes-golden-luxury': {
        id: 'boxes-golden-luxury',
        name: 'Golden Hour',
        category: 'modern',
        description: 'Identité luxueuse, tons chauds et typographie spacieuse',
        preview: {
            bgType: 'light',
            bgValue: '#FAF9F6',
            layoutType: 'grid',
            columns: 3,
            accentColor: '#D4AF37',
        },
        styles: {
            section: 'py-24 md:py-40 px-6 bg-[#FAF9F6]',
            container: 'max-w-6xl mx-auto',
            title: 'text-3xl md:text-5xl font-extralight tracking-[0.2em] text-[#1a1a1a] uppercase text-center mb-8',
            subtitle: 'text-xs font-black uppercase tracking-[0.4em] text-[#D4AF37] text-center mb-32',
            grid: 'grid grid-cols-1 md:grid-cols-3 gap-16',
            card: 'flex flex-col gap-8 items-center text-center group',
            badge: 'text-[10px] font-black uppercase tracking-[0.4em] text-[#D4AF37] mb-4',
            itemTitle: 'text-2xl font-light text-[#1a1a1a] tracking-widest uppercase',
            itemText: 'text-sm text-[#4a4a4a] leading-[2] font-light italic',
            icon: 'w-10 h-10 text-[#D4AF37] opacity-60 group-hover:opacity-100 transition-opacity',
        }
    },
}

export default boxesTemplates
