import type { BlockTemplateGroup } from './types'

// Types pour Pricing
export type PricingLayout = 'single' | 'comparison' | 'featured' | 'compact'

export const pricingTemplates: BlockTemplateGroup = {
  // ===== MINIMAL =====
  'pricing-minimal-centered': {
    id: 'pricing-minimal-centered',
    name: 'Minimal Centré',
    category: 'minimal',
    description: 'Prix épuré centré',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: false },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-lg mx-auto text-center',
      header: 'mb-10',
      title: 'text-2xl md:text-3xl font-light tracking-tight',
      subtitle: 'text-base opacity-60 mt-4',
      card: 'py-10',
      badge: 'hidden',
      priceWrapper: 'mb-6',
      originalPrice: 'text-lg opacity-50 line-through mb-1',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-light opacity-70 mr-1',
      price: 'text-5xl md:text-6xl font-light tracking-tight',
      period: 'text-base font-light opacity-50 mt-2',
      features: 'mt-8 space-y-3 text-sm opacity-70 text-left max-w-xs mx-auto',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-0.5',
      featureText: 'opacity-80',
      guarantee: 'hidden',
      button: 'mt-10 w-full py-4 text-sm font-medium uppercase tracking-widest border-2 transition-colors duration-200',
    }
  },
  'pricing-minimal-line': {
    id: 'pricing-minimal-line',
    name: 'Minimal Ligne',
    category: 'minimal',
    description: 'Prix avec séparateur',
    config: { layout: 'compact', showOriginalPrice: false, showPeriod: true, showFeatures: false, showGuarantee: false },
    styles: {
      section: 'py-12 md:py-16 px-6 border-t border-b',
      container: 'max-w-2xl mx-auto',
      header: 'mb-6',
      title: 'text-lg font-light tracking-tight',
      subtitle: 'hidden',
      card: 'flex flex-col md:flex-row items-center justify-between gap-6',
      badge: 'hidden',
      priceWrapper: '',
      originalPrice: 'hidden',
      priceRow: 'flex items-baseline',
      currency: 'text-lg font-light opacity-70 mr-1',
      price: 'text-4xl font-light tracking-tight',
      period: 'text-sm font-light opacity-50 ml-2',
      features: 'hidden',
      featureItem: '',
      featureIcon: '',
      featureText: '',
      guarantee: 'hidden',
      button: 'px-8 py-3 text-sm font-medium tracking-wide border transition-colors duration-200',
    }
  },
  'pricing-minimal-compact': {
    id: 'pricing-minimal-compact',
    name: 'Minimal Compact',
    category: 'minimal',
    description: 'Version très compacte',
    config: { layout: 'compact', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: false },
    styles: {
      section: 'py-10 md:py-14 px-6',
      container: 'max-w-md mx-auto text-center',
      header: 'mb-6',
      title: 'text-base font-light tracking-tight',
      subtitle: 'hidden',
      card: '',
      badge: 'hidden',
      priceWrapper: '',
      originalPrice: 'text-sm opacity-40 line-through',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-sm font-light opacity-70 mr-1',
      price: 'text-3xl font-normal tracking-tight',
      period: 'text-xs font-light opacity-50 mt-1',
      features: 'mt-4 text-xs opacity-60 space-y-1',
      featureItem: 'flex items-center justify-center gap-2',
      featureIcon: 'w-4 h-4',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-6 px-6 py-3 text-xs font-semibold uppercase tracking-widest border transition-colors duration-200',
    }
  },

  // ===== MODERN =====
  'pricing-modern-card': {
    id: 'pricing-modern-card',
    name: 'Modern Carte',
    category: 'modern',
    description: 'Carte de prix moderne',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-md mx-auto',
      header: 'text-center mb-10',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      card: 'border p-10',
      badge: 'absolute -top-3 left-1/2 -translate-x-1/2 px-4 py-1 text-xs font-semibold uppercase tracking-wide',
      priceWrapper: 'text-center mb-8',
      originalPrice: 'text-lg opacity-50 line-through mb-1',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-normal opacity-70 mr-1',
      price: 'text-5xl font-semibold tracking-tight',
      period: 'text-sm font-normal opacity-60 mt-2',
      features: 'space-y-4 text-sm',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-0.5',
      featureText: '',
      guarantee: 'mt-6 pt-6 border-t text-center text-xs opacity-60',
      button: 'mt-8 w-full py-4 text-sm font-semibold tracking-wide transition-colors duration-200',
    }
  },
  'pricing-modern-highlight': {
    id: 'pricing-modern-highlight',
    name: 'Modern Highlight',
    category: 'modern',
    description: 'Avec mise en avant',
    config: { layout: 'featured', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true, showBadgePopular: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-lg mx-auto',
      header: 'mb-10',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      card: 'border-2 p-10 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-6 py-2 text-sm font-semibold uppercase tracking-wide',
      priceWrapper: 'text-center mb-8',
      originalPrice: 'text-xl opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-semibold opacity-80 mr-1',
      price: 'text-5xl md:text-6xl font-bold tracking-tight',
      period: 'text-sm font-normal opacity-60 mt-2',
      features: 'space-y-4 text-base',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-1',
      featureText: '',
      guarantee: 'mt-8 pt-6 border-t text-center text-sm opacity-60',
      button: 'mt-10 w-full py-5 text-sm font-semibold uppercase tracking-wider transition-colors duration-200',
    }
  },
  'pricing-modern-split': {
    id: 'pricing-modern-split',
    name: 'Modern Split',
    category: 'modern',
    description: 'Prix et features séparés',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: false },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-3xl mx-auto',
      header: 'mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      card: 'grid md:grid-cols-2 gap-8 border p-8',
      badge: 'hidden',
      priceWrapper: '',
      originalPrice: 'text-lg opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline',
      currency: 'text-lg font-semibold opacity-70 mr-1',
      price: 'text-4xl md:text-5xl font-bold tracking-tight',
      period: 'text-sm font-normal opacity-60 mt-2',
      features: 'space-y-3 text-sm border-t md:border-t-0 md:border-l pt-6 md:pt-0 md:pl-8',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-8 md:col-span-2 w-full py-4 text-sm font-semibold tracking-wide transition-colors duration-200',
    }
  },
  'pricing-modern-detailed': {
    id: 'pricing-modern-detailed',
    name: 'Modern Détaillé',
    category: 'modern',
    description: 'Version complète détaillée',
    config: { layout: 'featured', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true, showBadgePopular: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-lg mx-auto',
      header: 'text-center mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-60 mt-4 max-w-md mx-auto',
      card: 'border p-8 md:p-12 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-6 py-2 text-sm font-semibold',
      priceWrapper: 'text-center mb-10',
      originalPrice: 'text-xl opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-2xl font-semibold opacity-80 mr-1',
      price: 'text-6xl md:text-7xl font-bold tracking-tight',
      period: 'text-base font-normal opacity-60 mt-3',
      features: 'space-y-4 text-base',
      featureItem: 'flex items-start gap-4',
      featureIcon: 'w-6 h-6 flex-shrink-0',
      featureText: '',
      guarantee: 'mt-8 p-4 border text-center text-sm',
      button: 'mt-10 w-full py-5 text-base font-semibold tracking-wide transition-colors duration-200',
    }
  },

  // ===== BOLD =====
  'pricing-bold-impact': {
    id: 'pricing-bold-impact',
    name: 'Bold Impact',
    category: 'bold',
    description: 'Prix à fort impact',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-xl mx-auto text-center',
      header: 'mb-12',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      card: '',
      badge: 'inline-block px-6 py-2 text-sm font-black uppercase tracking-widest mb-8',
      priceWrapper: 'mb-10',
      originalPrice: 'text-2xl opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-2xl font-bold opacity-80 mr-1',
      price: 'text-7xl md:text-8xl font-black tracking-tighter',
      period: 'text-lg font-bold opacity-60 mt-4 uppercase',
      features: 'space-y-4 text-lg font-medium text-left max-w-sm mx-auto',
      featureItem: 'flex items-start gap-4',
      featureIcon: 'w-6 h-6 flex-shrink-0',
      featureText: '',
      guarantee: 'mt-10 text-sm font-medium uppercase tracking-wide opacity-70',
      button: 'mt-14 w-full py-6 text-base font-bold uppercase tracking-widest transition-colors duration-200',
    }
  },
  'pricing-bold-boxed': {
    id: 'pricing-bold-boxed',
    name: 'Bold Encadré',
    category: 'bold',
    description: 'Encadré audacieux',
    config: { layout: 'featured', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true, showBadgePopular: true },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-lg mx-auto',
      header: 'mb-10',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-base opacity-70 mt-3',
      card: 'border-4 p-12 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-8 py-2 text-sm font-black uppercase tracking-widest border-4',
      priceWrapper: 'text-center mb-10',
      originalPrice: 'text-xl opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-bold mr-1',
      price: 'text-6xl md:text-7xl font-black tracking-tight',
      period: 'text-sm font-bold opacity-70 mt-3 uppercase tracking-wide',
      features: 'space-y-4 text-base font-medium',
      featureItem: 'flex items-start gap-4',
      featureIcon: 'w-6 h-6 flex-shrink-0',
      featureText: '',
      guarantee: 'mt-8 pt-6 border-t-4 text-center text-sm font-bold uppercase',
      button: 'mt-12 w-full py-5 text-sm font-black uppercase tracking-widest border-4 transition-colors duration-200',
    }
  },
  'pricing-bold-inverse': {
    id: 'pricing-bold-inverse',
    name: 'Bold Inverse',
    category: 'bold',
    description: 'Style inversé dramatique',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: false },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-md mx-auto text-center',
      header: 'mb-8',
      title: 'text-2xl md:text-3xl font-black tracking-tight uppercase',
      subtitle: 'text-base opacity-70 mt-3',
      card: 'p-12',
      badge: 'hidden',
      priceWrapper: 'mb-8',
      originalPrice: 'text-xl opacity-50 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-2xl font-black mr-1',
      price: 'text-6xl md:text-7xl font-black tracking-tighter leading-none',
      period: 'text-base font-bold mt-4 uppercase tracking-wider',
      features: 'space-y-3 text-sm font-medium text-left max-w-xs mx-auto',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-12 w-full py-5 text-sm font-black uppercase tracking-widest transition-colors duration-200',
    }
  },

  // ===== PREMIUM =====
  'pricing-premium-elegant': {
    id: 'pricing-premium-elegant',
    name: 'Premium Élégant',
    category: 'minimal',
    description: 'Style élégant raffiné',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-md mx-auto text-center',
      header: 'mb-14',
      title: 'text-2xl md:text-3xl font-light tracking-wide',
      subtitle: 'text-base font-light opacity-50 mt-4',
      card: 'py-12',
      badge: 'hidden',
      priceWrapper: 'mb-10',
      originalPrice: 'text-lg font-light opacity-40 line-through mb-2',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-light opacity-60 mr-2',
      price: 'text-6xl md:text-7xl font-extralight tracking-tight',
      period: 'text-sm font-light opacity-50 mt-3 tracking-wide',
      features: 'space-y-4 text-sm font-light opacity-70 text-left max-w-xs mx-auto',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-4 h-4 flex-shrink-0 mt-1 opacity-60',
      featureText: '',
      guarantee: 'mt-10 text-xs font-light opacity-40 tracking-wide',
      button: 'mt-12 w-full py-4 text-sm font-normal tracking-widest border transition-colors duration-200',
    }
  },
  'pricing-premium-showcase': {
    id: 'pricing-premium-showcase',
    name: 'Premium Showcase',
    category: 'modern',
    description: 'Présentation premium complète',
    config: { layout: 'featured', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true, showBadgePopular: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-lg mx-auto',
      header: 'text-center mb-14',
      title: 'text-3xl md:text-4xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-60 mt-4 max-w-md mx-auto',
      card: 'border p-10 md:p-14 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-8 py-2 text-sm font-semibold tracking-wide',
      priceWrapper: 'text-center mb-12',
      originalPrice: 'text-xl opacity-50 line-through mb-3',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-2xl font-semibold opacity-70 mr-2',
      price: 'text-6xl md:text-7xl font-bold tracking-tight',
      period: 'text-base font-normal opacity-60 mt-4',
      features: 'space-y-5 text-base',
      featureItem: 'flex items-start gap-4',
      featureIcon: 'w-6 h-6 flex-shrink-0',
      featureText: '',
      guarantee: 'mt-10 p-4 border text-center text-sm',
      button: 'mt-12 w-full py-5 text-base font-semibold tracking-wide transition-colors duration-200',
    }
  },
  'pricing-premium-luxury': {
    id: 'pricing-premium-luxury',
    name: 'Premium Luxe',
    category: 'modern',
    description: 'Style luxueux haut de gamme',
    config: { layout: 'featured', showOriginalPrice: true, showPeriod: true, showFeatures: true, showGuarantee: true, showBadgePopular: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-md mx-auto',
      header: 'text-center mb-16',
      title: 'text-2xl md:text-3xl font-medium tracking-wide',
      subtitle: 'text-base opacity-50 mt-4',
      card: 'border-2 p-12 md:p-16 relative',
      badge: 'absolute -top-5 left-1/2 -translate-x-1/2 px-8 py-3 text-xs font-medium uppercase tracking-[0.2em]',
      priceWrapper: 'text-center mb-12',
      originalPrice: 'text-lg opacity-40 line-through mb-3',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-xl font-medium opacity-60 mr-2',
      price: 'text-7xl md:text-8xl font-light tracking-tight',
      period: 'text-sm font-normal opacity-50 mt-4 tracking-wide',
      features: 'space-y-5 text-sm',
      featureItem: 'flex items-center gap-4',
      featureIcon: 'w-5 h-5 flex-shrink-0 opacity-70',
      featureText: 'tracking-wide',
      guarantee: 'mt-10 text-center text-xs tracking-wide opacity-50',
      button: 'mt-14 w-full py-5 text-sm font-medium uppercase tracking-[0.15em] transition-colors duration-200',
    }
  },

  // ===== NOUVEAUX TEMPLATES AVANCÉS =====
  'pricing-classic-cards': {
    id: 'pricing-classic-cards',
    name: 'Classic Cards',
    category: 'modern',
    description: '3 cartes classiques avec badge populaire',
    config: { layout: 'comparison', showOriginalPrice: false, showPeriod: true, showFeatures: true, showGuarantee: false },
    preview: { bgType: 'light', layoutType: 'grid', icon: 'grid' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-12',
      title: 'text-3xl md:text-4xl font-bold tracking-tight',
      subtitle: 'text-base opacity-60 mt-4',
      card: 'p-8 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1.5 text-xs font-semibold uppercase tracking-wide rounded-full',
      priceWrapper: 'mb-6',
      originalPrice: 'text-lg opacity-50 line-through mb-1',
      priceRow: 'flex items-baseline',
      currency: 'text-lg font-normal opacity-70',
      price: 'text-5xl font-bold tracking-tight',
      period: 'text-sm font-normal opacity-60 ml-1',
      features: 'space-y-3 text-sm',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-0.5',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-8 w-full py-3 text-sm font-medium tracking-wide transition-colors duration-200 rounded-lg',
    }
  },
  'pricing-simple-pyramid': {
    id: 'pricing-simple-pyramid',
    name: 'Simple Pyramid',
    category: 'minimal',
    description: 'Layout pyramide minimaliste',
    config: { layout: 'compact', showOriginalPrice: false, showPeriod: true, showFeatures: false, showGuarantee: false },
    preview: { bgType: 'light', layoutType: 'list', icon: 'card' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-4xl mx-auto',
      header: 'text-center mb-12',
      title: 'text-3xl md:text-4xl font-bold tracking-tight',
      subtitle: 'hidden',
      card: 'p-8 text-center',
      badge: 'hidden',
      priceWrapper: 'mb-4',
      originalPrice: 'hidden',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-lg font-normal opacity-70',
      price: 'text-5xl font-bold tracking-tight',
      period: 'text-sm font-normal opacity-60 ml-1',
      features: 'hidden',
      featureItem: '',
      featureIcon: '',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-4 w-full py-3 text-sm font-medium tracking-wide transition-colors duration-200 rounded-full',
    }
  },
  'pricing-flexible-toggle': {
    id: 'pricing-flexible-toggle',
    name: 'Flexible Toggle',
    category: 'modern',
    description: 'Toggle Mensuel/Annuel avec réduction',
    config: { layout: 'comparison', showOriginalPrice: false, showPeriod: true, showFeatures: true, showGuarantee: false, showBillingToggle: true },
    preview: { bgType: 'light', layoutType: 'grid', icon: 'grid' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-8',
      title: 'text-3xl md:text-4xl font-bold tracking-tight',
      subtitle: 'text-base opacity-60 mt-4',
      card: 'p-8 relative',
      badge: 'absolute -top-4 left-1/2 -translate-x-1/2 px-4 py-1.5 text-xs font-semibold uppercase tracking-wide rounded-full',
      priceWrapper: 'mb-6',
      originalPrice: 'text-lg opacity-50 line-through mb-1',
      priceRow: 'flex items-baseline',
      currency: 'text-lg font-normal opacity-70',
      price: 'text-5xl font-bold tracking-tight',
      period: 'text-sm font-normal opacity-60 ml-1',
      features: 'space-y-3 text-sm',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-0.5',
      featureText: '',
      guarantee: 'hidden',
      button: 'mt-8 w-full py-3 text-sm font-medium tracking-wide transition-colors duration-200 rounded-lg',
    }
  },
  'pricing-enterprise-split': {
    id: 'pricing-enterprise-split',
    name: 'Enterprise Split',
    category: 'modern',
    description: 'Solution entreprise avec formulaire contact',
    config: { layout: 'enterprise', showOriginalPrice: false, showPeriod: false, showFeatures: true, showGuarantee: false },
    preview: { bgType: 'light', layoutType: 'split-left', icon: 'split' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'mb-8',
      title: 'text-3xl md:text-4xl font-bold tracking-tight',
      subtitle: 'text-lg opacity-70 mt-4',
      card: 'p-8',
      badge: 'inline-block px-3 py-1 text-xs font-semibold uppercase tracking-wide rounded mb-6',
      priceWrapper: 'hidden',
      originalPrice: 'hidden',
      priceRow: 'hidden',
      currency: 'hidden',
      price: 'hidden',
      period: 'hidden',
      features: 'space-y-4 text-base',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-1',
      featureText: '',
      guarantee: 'hidden',
      button: 'w-full py-4 text-base font-semibold tracking-wide transition-colors duration-200 rounded-lg',
    }
  },
  'pricing-lifetime-deal': {
    id: 'pricing-lifetime-deal',
    name: 'Lifetime Deal',
    category: 'bold',
    description: 'Offre unique à vie avec urgence',
    config: { layout: 'single', showOriginalPrice: true, showPeriod: false, showFeatures: true, showGuarantee: true, showUrgency: true },
    preview: { bgType: 'gradient', layoutType: 'list', icon: 'star' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-lg mx-auto text-center',
      header: 'mb-8',
      title: 'text-3xl md:text-4xl font-bold tracking-tight',
      subtitle: 'text-lg opacity-70 mt-4',
      card: '',
      badge: 'inline-block px-5 py-2 text-sm font-bold uppercase tracking-wide rounded-full mb-6',
      priceWrapper: 'mb-8',
      originalPrice: 'text-xl opacity-50 line-through inline mr-3',
      priceRow: 'flex items-baseline justify-center',
      currency: 'text-2xl font-bold',
      price: 'text-6xl md:text-7xl font-black tracking-tight',
      period: 'hidden',
      features: 'space-y-3 text-base text-left max-w-sm mx-auto',
      featureItem: 'flex items-start gap-3',
      featureIcon: 'w-5 h-5 flex-shrink-0 mt-1',
      featureText: '',
      guarantee: 'mt-6 text-sm opacity-60',
      button: 'mt-8 w-full py-5 text-base font-bold tracking-wide transition-colors duration-200 rounded-xl',
    }
  },
}

export default pricingTemplates
