import type { BlockTemplateGroup } from './types'

// Types pour Testimonials
export type TestimonialsLayout = 'grid' | 'carousel' | 'single' | 'masonry' | 'list'
export type AvatarStyle = 'circle' | 'square' | 'none'

export const testimonialsTemplates: BlockTemplateGroup = {
  // ===== MINIMAL =====
  'testimonials-minimal-centered': {
    id: 'testimonials-minimal-centered',
    name: 'Minimal Centré',
    category: 'minimal',
    description: 'Témoignages épurés centrés',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-4xl mx-auto',
      header: 'text-center mb-12 md:mb-16',
      title: 'text-2xl md:text-3xl font-light tracking-tight',
      subtitle: 'text-base opacity-60 mt-4',
      grid: 'space-y-10',
      card: 'text-center',
      quoteIcon: 'w-8 h-8 mx-auto mb-4 opacity-20',
      quote: 'text-lg md:text-xl font-light leading-relaxed italic opacity-80',
      rating: 'flex justify-center gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-6 gap-3',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-minimal-grid': {
    id: 'testimonials-minimal-grid',
    name: 'Minimal Grille',
    category: 'minimal',
    description: 'Grille de témoignages simple',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: false },
    styles: {
      section: 'py-14 md:py-20 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'mb-10',
      title: 'text-xl md:text-2xl font-light tracking-tight',
      subtitle: 'text-sm opacity-60 mt-3',
      grid: 'grid grid-cols-1 md:grid-cols-2 gap-8',
      card: 'py-6 border-t',
      quoteIcon: 'hidden',
      quote: 'text-base font-light leading-relaxed opacity-70',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'hidden',
    }
  },
  'testimonials-minimal-single': {
    id: 'testimonials-minimal-single',
    name: 'Minimal Single',
    category: 'minimal',
    description: 'Un seul témoignage mis en avant',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false },
    styles: {
      section: 'py-12 md:py-16 px-6',
      container: 'max-w-2xl mx-auto text-center',
      header: 'mb-8',
      title: 'text-lg font-light tracking-tight',
      subtitle: 'hidden',
      grid: '',
      card: '',
      quoteIcon: 'w-10 h-10 mx-auto mb-6 opacity-10',
      quote: 'text-xl md:text-2xl font-light leading-relaxed',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-8 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'hidden',
    }
  },

  // ===== MODERN =====
  'testimonials-modern-cards': {
    id: 'testimonials-modern-cards',
    name: 'Modern Cartes',
    category: 'modern',
    description: 'Cartes modernes avec bordure',
    config: { layout: 'grid', columns: 3, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-3xl md:text-4xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-70 mt-4 max-w-2xl mx-auto',
      grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
      card: 'border p-8',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-6 gap-3',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-modern-accent': {
    id: 'testimonials-modern-accent',
    name: 'Modern Accent',
    category: 'modern',
    description: 'Avec accent coloré à gauche',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'space-y-8',
      card: 'border-l-4 pl-6 md:pl-8 py-4',
      quoteIcon: 'hidden',
      quote: 'text-lg leading-relaxed opacity-80',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-modern-carousel': {
    id: 'testimonials-modern-carousel',
    name: 'Modern Carousel',
    category: 'modern',
    description: 'Style carrousel horizontal',
    config: { layout: 'carousel', showAvatar: true, showRole: true, showRating: true },
    styles: {
      section: 'py-16 md:py-24 px-6 overflow-hidden',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'flex gap-6 overflow-x-auto pb-4 snap-x snap-mandatory scrollbar-hide -mx-6 px-6',
      card: 'flex-shrink-0 w-80 md:w-96 border p-6 snap-center',
      quoteIcon: 'hidden',
      quote: 'text-sm leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-3',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'hidden',
    }
  },
  'testimonials-modern-masonry': {
    id: 'testimonials-modern-masonry',
    name: 'Modern Masonry',
    category: 'modern',
    description: 'Layout Masonry dynamique',
    config: { layout: 'masonry', columns: 3, showAvatar: true, showRole: true, showRating: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6',
      card: 'break-inside-avoid border p-6',
      quoteIcon: 'hidden',
      quote: 'text-sm leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'hidden',
    }
  },
  'testimonials-modern-featured': {
    id: 'testimonials-modern-featured',
    name: 'Modern Featured',
    category: 'modern',
    description: 'Un témoignage mis en avant avec grille',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
      card: 'border p-8 first:md:col-span-2 first:text-center first:py-12',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80 first:text-xl',
      rating: 'flex gap-1 mt-4 first:justify-center',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-6 gap-3 first:justify-center',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },

  // ===== BOLD =====
  'testimonials-bold-quote': {
    id: 'testimonials-bold-quote',
    name: 'Bold Grande Citation',
    category: 'bold',
    description: 'Grande citation mise en avant',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-5xl mx-auto text-center',
      header: 'mb-16',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: '',
      card: '',
      quoteIcon: 'w-16 h-16 mx-auto mb-8 opacity-20',
      quote: 'text-3xl md:text-4xl lg:text-5xl font-bold leading-tight',
      rating: 'hidden',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center justify-center mt-12 gap-4',
      avatar: 'w-16 h-16 rounded-full',
      authorInfo: 'text-left',
      author: 'text-lg font-bold uppercase tracking-wide',
      role: 'text-sm opacity-70',
      company: 'text-sm opacity-50 font-medium',
    }
  },
  'testimonials-bold-split': {
    id: 'testimonials-bold-split',
    name: 'Bold Split',
    category: 'bold',
    description: 'Layout divisé audacieux',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: true },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'mb-14',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: 'grid grid-cols-1 lg:grid-cols-2 gap-8',
      card: 'p-10 md:p-12 border-4',
      quoteIcon: 'hidden',
      quote: 'text-xl md:text-2xl font-bold leading-tight',
      rating: 'flex gap-1 mt-6',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center mt-8 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: '',
      author: 'text-base font-bold uppercase',
      role: 'text-sm opacity-70',
      company: 'hidden',
    }
  },
  'testimonials-bold-fullwidth': {
    id: 'testimonials-bold-fullwidth',
    name: 'Bold Pleine Largeur',
    category: 'bold',
    description: 'Témoignages pleine largeur',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-7xl mx-auto',
      header: 'text-center mb-16',
      title: 'text-4xl md:text-5xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: 'space-y-0',
      card: 'py-12 border-b-4 last:border-b-0 flex flex-col md:flex-row items-center gap-8',
      quoteIcon: 'hidden',
      quote: 'text-xl md:text-2xl font-bold leading-tight flex-1',
      rating: 'hidden',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center gap-4 flex-shrink-0',
      avatar: 'w-20 h-20 rounded-full',
      authorInfo: '',
      author: 'text-lg font-bold uppercase tracking-wide',
      role: 'text-sm opacity-70',
      company: 'text-sm opacity-50',
    }
  },

  // ===== PREMIUM =====
  'testimonials-premium-elegant': {
    id: 'testimonials-premium-elegant',
    name: 'Premium Élégant',
    category: 'minimal',
    description: 'Style élégant raffiné',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-3xl mx-auto text-center',
      header: 'mb-12',
      title: 'text-2xl md:text-3xl font-light tracking-wide',
      subtitle: 'text-base font-light opacity-50 mt-4',
      grid: '',
      card: '',
      quoteIcon: 'w-12 h-12 mx-auto mb-8 opacity-10',
      quote: 'text-xl md:text-2xl font-light leading-relaxed italic',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-10 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium tracking-wide',
      role: 'text-xs opacity-50 mt-1',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-premium-showcase': {
    id: 'testimonials-premium-showcase',
    name: 'Premium Showcase',
    category: 'modern',
    description: 'Présentation premium',
    config: { layout: 'grid', columns: 3, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-16 md:mb-20',
      title: 'text-3xl md:text-4xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-60 mt-4 max-w-2xl mx-auto',
      grid: 'grid grid-cols-1 md:grid-cols-3 gap-8',
      card: 'p-8 border text-center',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80',
      rating: 'flex justify-center gap-1 mt-6',
      star: 'w-5 h-5',
      authorWrapper: 'flex flex-col items-center mt-6',
      avatar: 'w-16 h-16 rounded-full mb-4',
      authorInfo: 'text-center',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60 mt-1',
      company: 'text-xs opacity-40 mt-1',
    }
  },
}

export default testimonialsTemplates
