import type { BlockTemplateGroup } from './types'

// Types pour Testimonials
export type TestimonialsLayout = 'grid' | 'carousel' | 'single' | 'masonry' | 'list'
export type AvatarStyle = 'circle' | 'square' | 'none'

export const testimonialsTemplates: BlockTemplateGroup = {
  // ===== MINIMAL =====
  'testimonials-minimal-centered': {
    id: 'testimonials-minimal-centered',
    name: 'Minimal Centré',
    category: 'minimal',
    description: 'Témoignages épurés centrés',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false },
    preview: { bgType: 'light', layoutType: 'centered', icon: 'quote' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-4xl mx-auto',
      header: 'text-center mb-12 md:mb-16',
      title: 'text-2xl md:text-3xl font-light tracking-tight',
      subtitle: 'text-base opacity-60 mt-4',
      grid: 'space-y-10',
      card: 'text-center',
      quoteIcon: 'w-8 h-8 mx-auto mb-4 opacity-20',
      quote: 'text-lg md:text-xl font-light leading-relaxed italic opacity-80',
      rating: 'flex justify-center gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-6 gap-3',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-minimal-grid': {
    id: 'testimonials-minimal-grid',
    name: 'Minimal Grille',
    category: 'minimal',
    description: 'Grille de témoignages simple',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: false },
    preview: { bgType: 'light', layoutType: 'grid', icon: 'grid', columns: 2 },
    styles: {
      section: 'py-14 md:py-20 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'mb-10',
      title: 'text-xl md:text-2xl font-light tracking-tight',
      subtitle: 'text-sm opacity-60 mt-3',
      grid: 'grid grid-cols-1 md:grid-cols-2 gap-8',
      card: 'py-6 border-t',
      quoteIcon: 'hidden',
      quote: 'text-base font-light leading-relaxed opacity-70',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'hidden',
    }
  },
  'testimonials-minimal-single': {
    id: 'testimonials-minimal-single',
    name: 'Minimal Single',
    category: 'minimal',
    description: 'Un seul témoignage mis en avant',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false },
    preview: { bgType: 'light', layoutType: 'single', icon: 'quote' },
    styles: {
      section: 'py-12 md:py-16 px-6',
      container: 'max-w-2xl mx-auto text-center',
      header: 'mb-8',
      title: 'text-lg font-light tracking-tight',
      subtitle: 'hidden',
      grid: '',
      card: '',
      quoteIcon: 'w-10 h-10 mx-auto mb-6 opacity-10',
      quote: 'text-xl md:text-2xl font-light leading-relaxed',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-8 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium',
      role: 'text-xs opacity-50',
      company: 'hidden',
    }
  },

  // ===== MODERN =====
  'testimonials-modern-cards': {
    id: 'testimonials-modern-cards',
    name: 'Modern Cartes',
    category: 'modern',
    description: 'Cartes modernes avec bordure',
    config: { layout: 'grid', columns: 3, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    preview: { bgType: 'light', bgValue: '#f8fafc', layoutType: 'cards', icon: 'card', columns: 3 },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-3xl md:text-4xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-70 mt-4 max-w-2xl mx-auto',
      grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
      card: 'border p-8',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-6 gap-3',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-modern-accent': {
    id: 'testimonials-modern-accent',
    name: 'Modern Accent',
    category: 'modern',
    description: 'Avec accent coloré à gauche',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    preview: { bgType: 'light', layoutType: 'list', icon: 'list', accentColor: '#10b981' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'space-y-8',
      card: 'border-l-4 pl-6 md:pl-8 py-4',
      quoteIcon: 'hidden',
      quote: 'text-lg leading-relaxed opacity-80',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-modern-carousel': {
    id: 'testimonials-modern-carousel',
    name: 'Modern Carousel',
    category: 'modern',
    description: 'Style carrousel horizontal',
    config: { layout: 'carousel', showAvatar: true, showRole: true, showRating: true },
    preview: { bgType: 'light', layoutType: 'slider', icon: 'slider' },
    styles: {
      section: 'py-16 md:py-24 px-6 overflow-hidden',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-12',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'flex gap-6 overflow-x-auto pb-4 snap-x snap-mandatory scrollbar-hide -mx-6 px-6',
      card: 'flex-shrink-0 w-80 md:w-96 border p-6 snap-center',
      quoteIcon: 'hidden',
      quote: 'text-sm leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-3',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'hidden',
    }
  },
  'testimonials-modern-masonry': {
    id: 'testimonials-modern-masonry',
    name: 'Modern Masonry',
    category: 'modern',
    description: 'Layout Masonry dynamique',
    config: { layout: 'masonry', columns: 3, showAvatar: true, showRole: true, showRating: true },
    preview: { bgType: 'light', layoutType: 'grid', icon: 'grid', columns: 3 },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6',
      card: 'break-inside-avoid border p-6',
      quoteIcon: 'hidden',
      quote: 'text-sm leading-relaxed opacity-80',
      rating: 'flex gap-1 mt-4',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-4 gap-3',
      avatar: 'w-10 h-10 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'hidden',
    }
  },
  'testimonials-modern-featured': {
    id: 'testimonials-modern-featured',
    name: 'Modern Featured',
    category: 'modern',
    description: 'Un témoignage mis en avant avec grille',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    preview: { bgType: 'light', layoutType: 'split-left', icon: 'split' },
    styles: {
      section: 'py-16 md:py-24 px-6',
      container: 'max-w-5xl mx-auto',
      header: 'text-center mb-14',
      title: 'text-2xl md:text-3xl font-semibold tracking-tight',
      subtitle: 'text-base opacity-60 mt-3',
      grid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
      card: 'border p-8 first:md:col-span-2 first:text-center first:py-12',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80 first:text-xl',
      rating: 'flex gap-1 mt-4 first:justify-center',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center mt-6 gap-3 first:justify-center',
      avatar: 'w-12 h-12 rounded-full',
      authorInfo: '',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60',
      company: 'text-xs opacity-40',
    }
  },

  // ===== BOLD =====
  'testimonials-bold-quote': {
    id: 'testimonials-bold-quote',
    name: 'Bold Grande Citation',
    category: 'bold',
    description: 'Grande citation mise en avant',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false },
    preview: { bgType: 'dark', bgValue: '#1f2937', layoutType: 'centered', icon: 'quote' },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-5xl mx-auto text-center',
      header: 'mb-16',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: '',
      card: '',
      quoteIcon: 'w-16 h-16 mx-auto mb-8 opacity-20',
      quote: 'text-3xl md:text-4xl lg:text-5xl font-bold leading-tight',
      rating: 'hidden',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center justify-center mt-12 gap-4',
      avatar: 'w-16 h-16 rounded-full',
      authorInfo: 'text-left',
      author: 'text-lg font-bold uppercase tracking-wide',
      role: 'text-sm opacity-70',
      company: 'text-sm opacity-50 font-medium',
    }
  },
  'testimonials-bold-split': {
    id: 'testimonials-bold-split',
    name: 'Bold Split',
    category: 'bold',
    description: 'Layout divisé audacieux',
    config: { layout: 'grid', columns: 2, showAvatar: true, showRole: true, showRating: true },
    preview: { bgType: 'gradient', bgValue: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', layoutType: 'split-left', icon: 'split' },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'mb-14',
      title: 'text-3xl md:text-4xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: 'grid grid-cols-1 lg:grid-cols-2 gap-8',
      card: 'p-10 md:p-12 border-4',
      quoteIcon: 'hidden',
      quote: 'text-xl md:text-2xl font-bold leading-tight',
      rating: 'flex gap-1 mt-6',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center mt-8 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: '',
      author: 'text-base font-bold uppercase',
      role: 'text-sm opacity-70',
      company: 'hidden',
    }
  },
  'testimonials-bold-fullwidth': {
    id: 'testimonials-bold-fullwidth',
    name: 'Bold Pleine Largeur',
    category: 'bold',
    description: 'Témoignages pleine largeur',
    config: { layout: 'list', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    preview: { bgType: 'dark', bgValue: '#0f172a', layoutType: 'list', icon: 'list' },
    styles: {
      section: 'py-20 md:py-28 px-6',
      container: 'max-w-7xl mx-auto',
      header: 'text-center mb-16',
      title: 'text-4xl md:text-5xl font-black tracking-tight uppercase',
      subtitle: 'text-lg opacity-70 mt-4',
      grid: 'space-y-0',
      card: 'py-12 border-b-4 last:border-b-0 flex flex-col md:flex-row items-center gap-8',
      quoteIcon: 'hidden',
      quote: 'text-xl md:text-2xl font-bold leading-tight flex-1',
      rating: 'hidden',
      star: 'w-5 h-5',
      authorWrapper: 'flex items-center gap-4 flex-shrink-0',
      avatar: 'w-20 h-20 rounded-full',
      authorInfo: '',
      author: 'text-lg font-bold uppercase tracking-wide',
      role: 'text-sm opacity-70',
      company: 'text-sm opacity-50',
    }
  },

  // ===== PREMIUM =====
  'testimonials-premium-elegant': {
    id: 'testimonials-premium-elegant',
    name: 'Premium Élégant',
    category: 'minimal',
    description: 'Style élégant raffiné',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    preview: { bgType: 'light', bgValue: '#fafafa', layoutType: 'single', icon: 'quote' },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-3xl mx-auto text-center',
      header: 'mb-12',
      title: 'text-2xl md:text-3xl font-light tracking-wide',
      subtitle: 'text-base font-light opacity-50 mt-4',
      grid: '',
      card: '',
      quoteIcon: 'w-12 h-12 mx-auto mb-8 opacity-10',
      quote: 'text-xl md:text-2xl font-light leading-relaxed italic',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-10 gap-4',
      avatar: 'w-14 h-14 rounded-full',
      authorInfo: 'text-left',
      author: 'text-sm font-medium tracking-wide',
      role: 'text-xs opacity-50 mt-1',
      company: 'text-xs opacity-40',
    }
  },
  'testimonials-premium-showcase': {
    id: 'testimonials-premium-showcase',
    name: 'Premium Showcase',
    category: 'modern',
    description: 'Présentation premium',
    config: { layout: 'grid', columns: 3, showAvatar: true, showRole: true, showRating: true, showCompany: true },
    preview: { bgType: 'gradient', bgValue: 'linear-gradient(to bottom, #f8fafc, #e2e8f0)', layoutType: 'cards', icon: 'star', columns: 3 },
    styles: {
      section: 'py-20 md:py-32 px-6',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-16 md:mb-20',
      title: 'text-3xl md:text-4xl font-semibold tracking-tight',
      subtitle: 'text-lg opacity-60 mt-4 max-w-2xl mx-auto',
      grid: 'grid grid-cols-1 md:grid-cols-3 gap-8',
      card: 'p-8 border text-center',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed opacity-80',
      rating: 'flex justify-center gap-1 mt-6',
      star: 'w-5 h-5',
      authorWrapper: 'flex flex-col items-center mt-6',
      avatar: 'w-16 h-16 rounded-full mb-4',
      authorInfo: 'text-center',
      author: 'text-sm font-semibold',
      role: 'text-xs opacity-60 mt-1',
      company: 'text-xs opacity-40 mt-1',
    }
  },

  // ===== NOUVEAUX STYLES AVANCÉS =====
  
  // Style 1: Dark Slider - Fond sombre avec carrousel
  'testimonials-dark-slider': {
    id: 'testimonials-dark-slider',
    name: 'Dark Slider',
    category: 'bold',
    description: 'Carrousel élégant sur fond sombre',
    config: { layout: 'carousel', showAvatar: true, showRole: true, showRating: true, showCompany: true },
    preview: { bgType: 'dark', bgValue: '#1e293b', layoutType: 'slider', icon: 'slider' },
    styles: {
      section: 'py-20 md:py-28 px-6 bg-slate-800',
      container: 'max-w-4xl mx-auto text-center',
      header: 'mb-12',
      title: 'text-3xl md:text-4xl font-bold tracking-tight text-white',
      subtitle: 'text-base text-slate-400 mt-4',
      grid: 'relative',
      card: 'px-8 py-6',
      quoteIcon: 'hidden',
      quote: 'text-xl md:text-2xl font-light leading-relaxed italic text-slate-200',
      rating: 'flex justify-center gap-1 mb-6',
      star: 'w-5 h-5 text-amber-400',
      authorWrapper: 'flex items-center justify-center mt-8 gap-4',
      avatar: 'w-12 h-12 rounded-full bg-slate-600 flex items-center justify-center text-white font-semibold',
      authorInfo: 'text-left',
      author: 'text-base font-semibold text-white',
      role: 'text-sm text-slate-400',
      company: 'text-sm text-slate-500',
    }
  },

  // Style 2: Quote Large - Grande citation avec icône
  'testimonials-quote-large': {
    id: 'testimonials-quote-large',
    name: 'Quote Large',
    category: 'modern',
    description: 'Grande citation avec icône distinctive',
    config: { layout: 'single', showAvatar: true, showRole: true, showRating: false, showCompany: true },
    preview: { bgType: 'light', layoutType: 'centered', icon: 'quote' },
    styles: {
      section: 'py-20 md:py-28 px-6 bg-white',
      container: 'max-w-4xl mx-auto text-center',
      header: 'hidden',
      title: 'hidden',
      subtitle: 'hidden',
      grid: '',
      card: '',
      quoteIcon: 'w-20 h-20 mx-auto mb-8 text-gray-200',
      quote: 'text-2xl md:text-3xl font-light leading-relaxed italic text-gray-700',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'flex items-center justify-center mt-10 gap-4',
      avatar: 'w-14 h-14 rounded-full ring-4 ring-gray-100',
      authorInfo: 'text-left',
      author: 'text-lg font-semibold text-gray-900',
      role: 'text-sm text-gray-500',
      company: 'text-sm text-gray-400',
    }
  },

  // Style 3: Grid Compact - Grille compacte pour avis courts
  'testimonials-grid-compact': {
    id: 'testimonials-grid-compact',
    name: 'Grid Compact',
    category: 'modern',
    description: 'Grille compacte style avis produit',
    config: { layout: 'grid', columns: 3, showAvatar: false, showRole: false, showRating: true, showCompany: false },
    preview: { bgType: 'light', bgValue: '#fafafa', layoutType: 'grid', icon: 'grid', columns: 3 },
    styles: {
      section: 'py-16 md:py-24 px-6 bg-gray-50',
      container: 'max-w-6xl mx-auto',
      header: 'text-center mb-12',
      title: 'text-2xl md:text-3xl font-bold tracking-tight text-gray-900',
      subtitle: 'text-base text-gray-600 mt-3',
      grid: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
      card: 'bg-white p-6 rounded-xl border border-gray-200',
      quoteIcon: 'hidden',
      quote: 'text-sm leading-relaxed text-gray-700 mt-3',
      rating: 'flex gap-0.5',
      star: 'w-4 h-4 text-amber-400',
      authorWrapper: 'mt-4',
      avatar: 'hidden',
      authorInfo: '',
      author: 'text-sm font-medium text-gray-900',
      role: 'hidden',
      company: 'hidden',
    }
  },

  // Style 4: Split Image - Image grande + témoignage
  'testimonials-split-image': {
    id: 'testimonials-split-image',
    name: 'Split Image',
    category: 'bold',
    description: 'Grande image avec témoignage et statistiques',
    config: { layout: 'single', showAvatar: false, showRole: true, showRating: false, showCompany: true },
    preview: { bgType: 'light', layoutType: 'split-left', icon: 'split' },
    styles: {
      section: 'py-16 md:py-24 px-6 bg-white',
      container: 'max-w-6xl mx-auto',
      header: 'hidden',
      title: 'hidden',
      subtitle: 'hidden',
      grid: 'grid grid-cols-1 lg:grid-cols-2 gap-12 items-center',
      card: '',
      quoteIcon: 'w-12 h-12 text-gray-300 mb-6',
      quote: 'text-xl md:text-2xl font-normal leading-relaxed text-gray-700',
      rating: 'hidden',
      star: 'w-4 h-4',
      authorWrapper: 'mt-8',
      avatar: 'hidden',
      authorInfo: '',
      author: 'text-lg font-bold text-gray-900',
      role: 'text-sm text-gray-500',
      company: 'text-sm text-gray-400',
    }
  },

  // Style 5: Reviews List - Style avis vérifiés avec dates
  'testimonials-reviews-list': {
    id: 'testimonials-reviews-list',
    name: 'Reviews List',
    category: 'modern',
    description: 'Style avis vérifiés avec note moyenne',
    config: { layout: 'list', showAvatar: false, showRole: false, showRating: true, showCompany: false },
    preview: { bgType: 'light', layoutType: 'list', icon: 'star' },
    styles: {
      section: 'py-16 md:py-24 px-6 bg-white',
      container: 'max-w-3xl mx-auto',
      header: 'text-center mb-10',
      title: 'text-2xl md:text-3xl font-bold tracking-tight text-gray-900',
      subtitle: 'flex items-center justify-center gap-2 mt-3 text-lg',
      grid: 'space-y-4',
      card: 'bg-white p-6 rounded-xl border border-gray-200 relative',
      quoteIcon: 'hidden',
      quote: 'text-base leading-relaxed text-gray-700 mt-2',
      rating: 'flex gap-0.5',
      star: 'w-4 h-4 text-amber-400',
      authorWrapper: 'mt-3',
      avatar: 'hidden',
      authorInfo: '',
      author: 'text-sm font-medium text-gray-600',
      role: 'hidden',
      company: 'hidden',
    }
  },
}

export default testimonialsTemplates
